### PR TITLE
Remove census specific code

### PR DESCRIPTION
**Pull request by petechd**
### What is the context of this PR?
This removes census specific code from `survey.go` and `launch.html`. Some code was left in order to test census schemas (test_individual_response.json).

### How to review 
Use local go launcher as described in readme file to check the changes.

### CODE REVIEW

**Comment by petechd** [comment]
[Remove Census schema resolver from Runner and re-introduce business schema resolver](https://trello.com/c/yTQIFVeW/4726-remove-census-schema-resolver-from-runner-and-re-introduce-business-schema-resolver)

**Review by ajmaddaford — COMMENTED** [review]
There is still a fair bit of Census specific code e.g. `TransformSchemaParamsToName` in `auth.go` and Javascript in `launch.html`.

**Comment by petechd** [comment]
> TransformSchemaParamsToName

I removed census code from "auth.go" but do we want to remove the code in "launch.html" as it's required for launching "test_individual_response" schema?

**Comment by petechd** [comment]
Removed remaining census functions from "launch.go"

**Review by ajmaddaford — APPROVED** [review]

**Review by JamesGardiner — APPROVED** [review]

**Pull request merged**
